export const templates = [
  {
    id: "note",
    category: "写作",
    name: "灵感笔记",
    description: "让稍纵即逝的想法，有迹可循",
    icon: "markdown" as const,
    type: "markdown",
    language: "",
    title: "留给未来的一封短笺",
    content:
      "# 留给未来的一封短笺\n\n每个好想法，都值得被记下来。\n\n## 今天的灵感\n\n- [ ] 写下一个新想法\n- [ ] 把它变成一个小小的开始\n- [ ] 分享给有共鸣的人\n\n> 不必等到完美，现在就开始。\n\n---\n\n记录于星穹之间 ✦",
  },
  {
    id: "code",
    category: "开发",
    name: "代码片段",
    description: "分享一个解法，少一点重复劳动",
    icon: "code" as const,
    type: "code",
    language: "typescript",
    title: "一个小小的开始.ts",
    content:
      'type Idea = {\n  title: string;\n  shared: boolean;\n};\n\nconst idea: Idea = {\n  title: "Make something wonderful",\n  shared: true,\n};\n\nconsole.log(idea.title);',
  },
  {
    id: "math",
    category: "学习",
    name: "公式手记",
    description: "推导与思考，都能优雅呈现",
    icon: "text" as const,
    type: "markdown",
    language: "",
    title: "公式与一点点好奇心",
    content:
      "# 公式与一点点好奇心\n\n行内公式：$E = mc^2$。\n\n## 一个经典的恒等式\n\n$$\ne^{i\\pi} + 1 = 0\n$$\n\n## 高斯积分\n\n$$\n\\int_{-\\infty}^{+\\infty} e^{-x^2}\\,dx = \\sqrt{\\pi}\n$$\n\n把推导过程写在这里……",
  },
  {
    id: "meeting",
    category: "协作",
    name: "会议纪要",
    description: "共识、行动项，一次整理清楚",
    icon: "file" as const,
    type: "markdown",
    language: "",
    title: "会议纪要",
    content:
      "# 会议纪要\n\n**日期**：\n**参与者**：\n\n## 讨论事项\n\n1. \n2. \n\n## 形成的共识\n\n> 把重要的决定记在这里。\n\n## 下一步\n\n| 任务 | 负责人 | 截止时间 |\n| --- | --- | --- |\n|  |  |  |\n\n- [ ] 确认行动项\n- [ ] 同步给相关伙伴",
  },
  {
    id: "readme",
    category: "开发",
    name: "项目 README",
    description: "简介、安装与用法，一份齐备的开场白",
    icon: "code",
    type: "markdown",
    language: "",
    title: "项目 README",
    content:
      "# 项目名称\n\n> 用一句话描述这个项目解决的问题。\n\n## 功能\n\n- 功能一\n- 功能二\n\n## 快速开始\n\n```bash\nnpm install\nnpm run dev\n```\n\n## 使用方法\n\n说明输入、输出和一个最小示例。\n\n## 配置\n\n| 参数 | 说明 | 默认值 |\n| --- | --- | --- |\n| PORT | 本地端口 | 3000 |\n\n## 贡献与许可\n\n补充贡献方式和许可证。",
  },
  {
    id: "bug",
    category: "开发",
    name: "问题反馈",
    description: "用可复现的步骤，让问题更快解决",
    icon: "terminal",
    type: "markdown",
    language: "",
    title: "问题反馈",
    content:
      "# 问题反馈\n\n## 环境\n\n- 操作系统：\n- 浏览器 / 版本：\n- 应用版本：\n\n## 问题描述\n\n实际发生了什么？\n\n## 复现步骤\n\n1. 打开……\n2. 点击……\n3. 观察……\n\n## 预期行为\n\n期望得到什么结果？\n\n## 日志\n\n```text\n在这里粘贴脱敏日志\n```\n\n- [ ] 已移除密码、令牌与个人信息",
  },
  {
    id: "json",
    category: "开发",
    name: "JSON 数据",
    description: "整理接口示例，配合无损格式化工具",
    icon: "code",
    type: "code",
    language: "json",
    title: "接口响应示例.json",
    content:
      '{\n  "success": true,\n  "data": {\n    "id": "example-001",\n    "title": "一个新的想法",\n    "tags": ["note", "shared"],\n    "items": [{ "name": "示例", "enabled": true }]\n  }\n}',
  },
  {
    id: "api",
    category: "开发",
    name: "接口说明",
    description: "请求、响应、错误码，一次讲清",
    icon: "terminal",
    type: "markdown",
    language: "",
    title: "API 接口说明",
    content:
      '# API 接口说明\n\n## 获取示例\n\n`GET /api/example`\n\n### 请求参数\n\n| 字段 | 类型 | 必填 | 说明 |\n| --- | --- | --- | --- |\n| id | string | 是 | 对象 ID |\n\n### 响应示例\n\n```json\n{ "success": true, "data": { "id": "example" } }\n```\n\n### 错误码\n\n| 状态码 | 含义 |\n| --- | --- |\n| 400 | 参数错误 |\n| 404 | 对象不存在 |\n\n## 注意事项\n\n补充鉴权、限流与兼容性要求。',
  },
  {
    id: "study",
    category: "学习",
    name: "学习卡片",
    description: "概念、例子和自测，把知识变成自己的",
    icon: "file",
    type: "markdown",
    language: "",
    title: "学习卡片",
    content:
      "# 今天学会了什么\n\n## 核心概念\n\n用自己的话解释它：\n\n## 一个例子\n\n```text\n把抽象概念变成具体例子\n```\n\n## 易错点\n\n- \n\n## 自测\n\n- [ ] 不看笔记解释这个概念\n- [ ] 独立完成一个例题\n- [ ] 能说明它与相近概念的区别\n\n## 参考资料\n\n- [资料名称](https://example.com)",
  },
  {
    id: "reading",
    category: "学习",
    name: "阅读摘记",
    description: "留下一句触动，写下自己的思考",
    icon: "bookmark",
    type: "markdown",
    language: "",
    title: "阅读摘记",
    content:
      "# 阅读摘记\n\n**书名 / 文章**：\n**作者**：\n**日期**：\n\n## 三个关键词\n\n1. \n2. \n3. \n\n## 核心观点\n\n用自己的话归纳。\n\n## 我的思考\n\n什么让我赞同、疑惑，或想继续研究？\n\n## 下一步行动\n\n- [ ] 做一件可以实践的小事",
  },
  {
    id: "weekly",
    category: "协作",
    name: "周报复盘",
    description: "成果、问题与下周计划，清晰对齐",
    icon: "list",
    type: "markdown",
    language: "",
    title: "本周复盘",
    content:
      "# 本周复盘\n\n**周期**：\n\n## 已完成\n\n- [x] 一项重要的进展\n- [ ] 尚待完成的任务\n\n## 收获与数据\n\n| 项目 | 结果 | 备注 |\n| --- | --- | --- |\n|  |  |  |\n\n## 问题与支持\n\n遇到什么阻碍，需要怎样的协助？\n\n## 下周重点\n\n1. 最重要的一件事\n2. 其次值得推进的事\n\n## 给自己的一句话\n\n> 持续前进，也记得好好休息。",
  },
  {
    id: "checklist",
    category: "写作",
    name: "轻量清单",
    description: "纯文本待办，随手记下下一步",
    icon: "text",
    type: "plain",
    language: "",
    title: "今天的小清单",
    content:
      "今天的小清单\n============\n\n最重要的一件事：\n\n[ ] 第一件事\n[ ] 第二件事\n[ ] 第三件事\n\n随手记录\n--------\n\n完成后给自己一个小奖励。",
  },
{
  "id": "prompt",
  "category": "写作",
  "name": "AI 提示词",
  "description": "目标、背景、约束与输出格式，一次讲清",
  "icon": "star",
  "type": "markdown",
  "language": "",
  "title": "一份清晰的提示词",
  "content": "# 一份清晰的提示词\n\n## 目标\n\n我希望完成：\n\n## 背景与材料\n\n请在这里补充上下文。\n\n## 约束\n\n- 面向的读者：\n- 语气和长度：\n- 必须遵守的边界：\n\n## 输出格式\n\n请按以下结构输出：\n1. 结论\n2. 依据\n3. 可执行步骤\n\n## 验收标准\n\n- [ ] 事实有依据\n- [ ] 步骤可以执行\n- [ ] 不确定之处已标明"
},
{
  "id": "decision",
  "category": "协作",
  "name": "决策记录",
  "description": "记录为什么这样选，方便未来回看",
  "icon": "list",
  "type": "markdown",
  "language": "",
  "title": "一项决定的来龙去脉",
  "content": "# 决策记录\n\n**日期**：\n**状态**：待讨论\n\n## 要解决的问题\n\n用一段话描述当前处境。\n\n## 可选方案\n\n| 方案 | 优点 | 代价 |\n| --- | --- | --- |\n| A | | |\n| B | | |\n\n## 我们的决定\n\n选择：\n理由：\n\n## 后续观察\n\n- [ ] 确认实施负责人\n- [ ] 约定复盘日期"
},
{
  "id": "changelog",
  "category": "开发",
  "name": "更新日志",
  "description": "新增、修复与升级说明，清楚发布",
  "icon": "archive",
  "type": "markdown",
  "language": "",
  "title": "版本更新日志",
  "content": "# 更新日志\n\n## 版本号 · 日期\n\n### 新增\n\n- 一项值得关注的新功能\n\n### 改进\n\n- 一个更顺手的体验\n\n### 修复\n\n- 一处已经解决的问题\n\n### 升级说明\n\n是否有需要用户留意的变化？\n\n### 验证\n\n- [ ] 主要流程已验证\n- [ ] 回退方式已保留"
},
{
  "id": "comparison",
  "category": "学习",
  "name": "方案比较",
  "description": "把比较维度摆出来，减少纠结",
  "icon": "grid",
  "type": "markdown",
  "language": "",
  "title": "选一个更合适的方案",
  "content": "# 方案比较\n\n## 我真正需要什么\n\n- 必须满足：\n- 希望具备：\n- 可接受的代价：\n\n## 对照表\n\n| 维度 | 方案 A | 方案 B |\n| --- | --- | --- |\n| 使用成本 | | |\n| 上手难度 | | |\n| 长期维护 | | |\n| 关键限制 | | |\n\n## 结论\n\n我的选择：\n依据：\n\n## 仍待确认\n\n- [ ] 补充证据来源"
},
{
  "id": "curl",
  "category": "开发",
  "name": "HTTP 请求",
  "description": "一份可编辑的 cURL 请求示例",
  "icon": "terminal",
  "type": "code",
  "language": "bash",
  "title": "请求示例.sh",
  "content": "# 把地址替换为自己的接口；请勿在公开片段中填写真实令牌。\ncurl --request POST \\\n  --url https://example.com/api/items \\\n  --header \"Content-Type: application/json\" \\\n  --data '{\n    \"title\": \"A little idea\",\n    \"enabled\": true\n  }'\n"
},
{
  "id": "study-plan",
  "category": "学习",
  "name": "学习计划",
  "description": "目标、练习与复盘，稳稳推进",
  "icon": "bookmark",
  "type": "markdown",
  "language": "",
  "title": "一周学习计划",
  "content": "# 一周学习计划\n\n## 本周目标\n\n到本周结束，我希望能够：\n\n## 学习安排\n\n| 日期 | 内容 | 练习 | 完成 |\n| --- | --- | --- | --- |\n| 周一 | | | ☐ |\n| 周三 | | | ☐ |\n| 周五 | | | ☐ |\n\n## 学习材料\n\n- 材料名称与链接\n\n## 自测问题\n\n1. 能否用自己的话解释？\n2. 能否独立完成一次练习？\n\n## 周末复盘\n\n- 学会了什么：\n- 哪一点还不清楚：\n- 下周调整："
},
] as const;
export const typeLabels: Record<string, string> = {
  markdown: "Markdown",
  code: "代码",
  plain: "纯文本",
};
